server:
  port: 8080
  servlet:
    context-path: /price

spring:
  devtools:
    add-properties: false
  application:
    name: Pricing Engine
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  data:
    redis:
      host: localhost  # Redis server host
      port: 6379       # Redis server port
      password:        # Redis server password (if any)
      database: 0      # Redis database index (0-15)
      timeout: 60000   # Connection timeout in milliseconds
      lettuce:
        pool:
          maxActive: 8   # Maximum number of connections that can be allocated
          max-idle: 8     # Maximum number of idle connections
          min-idle: 0     # Minimum number of idle connections
          maxWait: -1ms  # Maximum amount of time to wait for a connection (-1 for no limit)

    mongodb:
      host: localhost
      port: 27017
      uri: mongodb://localhost:27017/pricingengine
      authentication-database: admin
      connection-timeout: 2000
      socket-timeout: 2000
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      enable-auto-commit: false
      auto-commit-interval-ms: 100
      session-timeout-ms: 15000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: group1
      auto-offset-reset: earliest
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB






logging:
  level:
    root: info
    org.springframework.web: warn
    org.hibernate: error
    com.tata.cliq: debug
  file:
    name: logs/PricingEngineApplication.log
  logback:
    rollingpolicy:
      file-name-pattern: logs/PricingEngineApplication-%d{yyyy-MM-dd}.%i.log
      max-file-size: 10MB
      max-history: 30

buybox:
  price:
    coefficient:
      for:
        nonjewellery: -0.00000001
        jewellery: 0.00000001
    addition:
      coefficient:
        for:
          weightage: 0
  cronjob:
    max:
      thread:
        count: 10

management:
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5, 0.75, 0.95, 0.99
      sla:
        http.server.requests: 10ms, 100ms
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,heartbeat
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      metrics:
        exporter:
          enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  observations:
    http:
      server:
        requests:
          percentiles: 0.5, 0.75, 0.95, 0.99
          service-level-objectives: 50ms, 100ms, 200ms

scheduler:
  interval: 5000000




resilience4j:
  circuitbreaker:
    instances:
      backendA:
        registerHealthIndicator: true
        slidingWindowSize: 100
  retry:
    instances:
      backendA:
        maxAttempts: 3
        waitDuration: 10s
  ratelimiter:
    instances:
      backendA:
        limitForPeriod: 10
        limitRefreshPeriod: 1s
        timeoutDuration: 1s
  bulkhead:
    instances:
      backendA:
        maxConcurrentCalls: 10

# Heartbeat configuration
heartbeat:
  interval: 5000 # milliseconds

# Swagger (OpenAPI) configurations
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: true
  packages-to-scan: com.tata.cliq.controller
  paths-to-match: /**

# OpenAPI custom properties
openapi:
  project-title: Pricing Engine API
  project-version: 1.0.0
  project-description: API documentation for the Pricing Engine
  team-name: Pricing Team
  developer-name: Tata Cliq Development Team
  developer-email: dev@tatacliq.com

# Commented out sections remain the same

project:
  contributors:
    - name: Prakash Ponali
      role: Project Lead
    - name: Saurav Menon
      role: Developer
    - name: Mayur
      role: Tester
